version: 2
jobs:
  terraform:
    docker:
      - image: hashicorp/terraform
        environment:
          AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run:
          name: Set variables
          command: cd terraform/test && cp backend.tfvars.example backend.tfvars && cp terraform.tfvars.example terraform.tfvars
      - run:
          name: EKK Stack - Set up Terraform
          command: terraform init -backend=false test
      - run:
          name: EKK Stack - Validate Terraform
          command: terraform validate -check-variables=false test

workflows:
  version: 2

  validate:
    jobs:
      - terraform
