version: 2
jobs:
  terraform:
    docker:
      - image: hashicorp/terraform
        environment:
          AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run:
          name: Validate main terraform
          command: cd terraform && cp test/terraform.tfvars.example terraform.tfvars && terraform validate
      - run:
          name: Set variables
          command: cd terraform/test && cp backend.tfvars.example backend.tfvars && cp terraform.tfvars.example terraform.tfvars
      - run:
          name: EKK Stack - Set up Terraform
          command: cd terraform/test && terraform init -backend=false
      - run:
          name: EKK Stack - Validate Terraform
          command: cd terraform/test && terraform validate

workflows:
  version: 2

  validate:
    jobs:
      - terraform
